//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Project/Settings/InputControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputControls"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""fd62e94d-83c1-4286-b165-1f3499de2bb0"",
            ""actions"": [
                {
                    ""name"": ""SendCommand"",
                    ""type"": ""Button"",
                    ""id"": ""23bf4e16-14a1-474b-b80a-9ba3da3c1fc0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EnableCommendQueuing"",
                    ""type"": ""Button"",
                    ""id"": ""aa97e346-a200-4bdd-bf79-1c31341603f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""d73c23ae-089c-4e7b-a847-9107d23df77f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectSame"",
                    ""type"": ""Button"",
                    ""id"": ""c90dbfba-d638-4fd8-8a9a-194c182b1791"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap(tapDelay=0.35)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StartSelecting"",
                    ""type"": ""Button"",
                    ""id"": ""7fcdf546-9241-4f7e-9f37-a51d30753833"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StopSelecting"",
                    ""type"": ""Button"",
                    ""id"": ""3a0172d6-95e7-4099-9e3f-1b8f1fd730f9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""c1b1734c-1140-4eec-b0fb-742f4bd70166"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SaveSelectionGroup"",
                    ""type"": ""Button"",
                    ""id"": ""70ee3ca6-87a6-45cf-bd76-5ed126c256f3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectionGroup1"",
                    ""type"": ""Button"",
                    ""id"": ""5fe60bf0-c65a-40fa-8733-f1a641bc3515"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectionGroup2"",
                    ""type"": ""Button"",
                    ""id"": ""59885f15-6116-434c-8639-42f994b75891"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectionGroup3"",
                    ""type"": ""Button"",
                    ""id"": ""a2721bc1-bfc8-48d0-aac1-cc6f5c39a0b5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectionGroup4"",
                    ""type"": ""Button"",
                    ""id"": ""9c536be7-3103-4e4e-ac68-9c17e8583f34"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectionGroup5"",
                    ""type"": ""Button"",
                    ""id"": ""cd3332e4-04f4-435d-9a3a-3103ce6f36dd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectionGroup6"",
                    ""type"": ""Button"",
                    ""id"": ""8fcda08a-3244-4c8a-8b7d-d81bf0ea07f8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectionGroup7"",
                    ""type"": ""Button"",
                    ""id"": ""f37cdedc-5d00-4c25-ba31-e866c0d06ac1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectionGroup8"",
                    ""type"": ""Button"",
                    ""id"": ""1944d9c5-5431-4984-b95e-43b14dc045bc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectionGroup9"",
                    ""type"": ""Button"",
                    ""id"": ""9faabd42-cca3-4be2-a868-240f891b3132"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectionGroup10"",
                    ""type"": ""Button"",
                    ""id"": ""88564dec-e7b3-43f1-8318-a14839e11778"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c3df95ed-b334-46dc-8aa7-5672ba6a9173"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SendCommand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4e590ed-abc1-4fe1-9376-1682bc8e5470"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnableCommendQueuing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f206c40-021a-4f04-810f-aa4fa17851d0"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""466f65d8-c4d6-4645-88cf-6e089187a60d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectSame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b4fd832-74b6-455b-95a1-9af65974f224"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartSelecting"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75ea9e1c-cde5-4399-86a7-21fbfbb984a0"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StopSelecting"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f571fdeb-ae5a-4907-b2f3-c73f1168ea92"",
                    ""path"": ""<Keyboard>/pause"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e44f20eb-7e2a-4af1-9c9d-1d7ebe7fb720"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SaveSelectionGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a3cdc54-bf8e-4c4b-8473-ae0c3503572d"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectionGroup1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3764737e-1c0c-46ed-984a-b4d26fd83578"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectionGroup2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c2eee9ec-d3de-4c28-b688-fc9db45dc222"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectionGroup3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91975025-333b-42c5-a656-73ff94b18a56"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectionGroup4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62585aa7-9f3e-44c3-a63c-98672fa144ef"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectionGroup5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e9577b80-bd17-48e7-b8da-b1d5688b0bdc"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectionGroup6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f5fee91-6a63-40ea-9eca-c2f7f1d2a161"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectionGroup7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39e95503-1569-43ea-bc16-b14271ee4324"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectionGroup8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9707aebc-2ed1-47c7-8db3-859e6f166b72"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectionGroup9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""73666b97-2341-445f-88e8-3cecadf2ae55"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectionGroup10"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Camera"",
            ""id"": ""4fa9c010-f1d2-4c71-bce7-83aa4c660c3f"",
            ""actions"": [
                {
                    ""name"": ""Focus"",
                    ""type"": ""Button"",
                    ""id"": ""5464a8a7-9840-448f-9f66-9a514f0c9857"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""PassThrough"",
                    ""id"": ""03320fc5-8b34-4076-8478-9ed89d50ccba"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": ""Clamp(min=-1,max=1)"",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ScreenPosition"",
                    ""type"": ""Value"",
                    ""id"": ""e7fae129-cce3-4c2c-b96c-22d503da83ef"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraRotationDirection"",
                    ""type"": ""Value"",
                    ""id"": ""bbfb9165-b74e-4c8c-a8f9-19167fb7522a"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": ""Clamp(min=-1,max=1)"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""EnableCameraRotation"",
                    ""type"": ""Button"",
                    ""id"": ""291c9503-3aae-47aa-ae4f-f43374094915"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c5c3aacc-9843-4671-b8b0-d11fd9f1730f"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Focus"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46ef788c-3539-4768-87e9-d07d32218aaf"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""efef31de-e6de-4887-978d-feea7e2a16fc"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScreenPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00856612-2f55-476e-b48c-82b3de2b4bad"",
                    ""path"": ""<Mouse>/delta/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraRotationDirection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""292dcaa5-38b3-456e-86c2-21bb54f11ba2"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnableCameraRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Menu"",
            ""id"": ""c02f7617-7776-47ae-8fe6-ce99309f68bc"",
            ""actions"": [
                {
                    ""name"": ""Close"",
                    ""type"": ""Button"",
                    ""id"": ""64e6f3c2-31c4-4a02-848f-d9e3010c9e6b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ScreenPosition"",
                    ""type"": ""Value"",
                    ""id"": ""8369877b-8153-4190-9238-543b58d439ed"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4207d6af-8a2f-424c-9ad6-9c400943abdb"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Close"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f81e33e-fe49-48ff-814b-65aab1ae8f74"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScreenPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_SendCommand = m_Player.FindAction("SendCommand", throwIfNotFound: true);
        m_Player_EnableCommendQueuing = m_Player.FindAction("EnableCommendQueuing", throwIfNotFound: true);
        m_Player_Cancel = m_Player.FindAction("Cancel", throwIfNotFound: true);
        m_Player_SelectSame = m_Player.FindAction("SelectSame", throwIfNotFound: true);
        m_Player_StartSelecting = m_Player.FindAction("StartSelecting", throwIfNotFound: true);
        m_Player_StopSelecting = m_Player.FindAction("StopSelecting", throwIfNotFound: true);
        m_Player_Pause = m_Player.FindAction("Pause", throwIfNotFound: true);
        m_Player_SaveSelectionGroup = m_Player.FindAction("SaveSelectionGroup", throwIfNotFound: true);
        m_Player_SelectionGroup1 = m_Player.FindAction("SelectionGroup1", throwIfNotFound: true);
        m_Player_SelectionGroup2 = m_Player.FindAction("SelectionGroup2", throwIfNotFound: true);
        m_Player_SelectionGroup3 = m_Player.FindAction("SelectionGroup3", throwIfNotFound: true);
        m_Player_SelectionGroup4 = m_Player.FindAction("SelectionGroup4", throwIfNotFound: true);
        m_Player_SelectionGroup5 = m_Player.FindAction("SelectionGroup5", throwIfNotFound: true);
        m_Player_SelectionGroup6 = m_Player.FindAction("SelectionGroup6", throwIfNotFound: true);
        m_Player_SelectionGroup7 = m_Player.FindAction("SelectionGroup7", throwIfNotFound: true);
        m_Player_SelectionGroup8 = m_Player.FindAction("SelectionGroup8", throwIfNotFound: true);
        m_Player_SelectionGroup9 = m_Player.FindAction("SelectionGroup9", throwIfNotFound: true);
        m_Player_SelectionGroup10 = m_Player.FindAction("SelectionGroup10", throwIfNotFound: true);
        // Camera
        m_Camera = asset.FindActionMap("Camera", throwIfNotFound: true);
        m_Camera_Focus = m_Camera.FindAction("Focus", throwIfNotFound: true);
        m_Camera_Zoom = m_Camera.FindAction("Zoom", throwIfNotFound: true);
        m_Camera_ScreenPosition = m_Camera.FindAction("ScreenPosition", throwIfNotFound: true);
        m_Camera_CameraRotationDirection = m_Camera.FindAction("CameraRotationDirection", throwIfNotFound: true);
        m_Camera_EnableCameraRotation = m_Camera.FindAction("EnableCameraRotation", throwIfNotFound: true);
        // Menu
        m_Menu = asset.FindActionMap("Menu", throwIfNotFound: true);
        m_Menu_Close = m_Menu.FindAction("Close", throwIfNotFound: true);
        m_Menu_ScreenPosition = m_Menu.FindAction("ScreenPosition", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_SendCommand;
    private readonly InputAction m_Player_EnableCommendQueuing;
    private readonly InputAction m_Player_Cancel;
    private readonly InputAction m_Player_SelectSame;
    private readonly InputAction m_Player_StartSelecting;
    private readonly InputAction m_Player_StopSelecting;
    private readonly InputAction m_Player_Pause;
    private readonly InputAction m_Player_SaveSelectionGroup;
    private readonly InputAction m_Player_SelectionGroup1;
    private readonly InputAction m_Player_SelectionGroup2;
    private readonly InputAction m_Player_SelectionGroup3;
    private readonly InputAction m_Player_SelectionGroup4;
    private readonly InputAction m_Player_SelectionGroup5;
    private readonly InputAction m_Player_SelectionGroup6;
    private readonly InputAction m_Player_SelectionGroup7;
    private readonly InputAction m_Player_SelectionGroup8;
    private readonly InputAction m_Player_SelectionGroup9;
    private readonly InputAction m_Player_SelectionGroup10;
    public struct PlayerActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @SendCommand => m_Wrapper.m_Player_SendCommand;
        public InputAction @EnableCommendQueuing => m_Wrapper.m_Player_EnableCommendQueuing;
        public InputAction @Cancel => m_Wrapper.m_Player_Cancel;
        public InputAction @SelectSame => m_Wrapper.m_Player_SelectSame;
        public InputAction @StartSelecting => m_Wrapper.m_Player_StartSelecting;
        public InputAction @StopSelecting => m_Wrapper.m_Player_StopSelecting;
        public InputAction @Pause => m_Wrapper.m_Player_Pause;
        public InputAction @SaveSelectionGroup => m_Wrapper.m_Player_SaveSelectionGroup;
        public InputAction @SelectionGroup1 => m_Wrapper.m_Player_SelectionGroup1;
        public InputAction @SelectionGroup2 => m_Wrapper.m_Player_SelectionGroup2;
        public InputAction @SelectionGroup3 => m_Wrapper.m_Player_SelectionGroup3;
        public InputAction @SelectionGroup4 => m_Wrapper.m_Player_SelectionGroup4;
        public InputAction @SelectionGroup5 => m_Wrapper.m_Player_SelectionGroup5;
        public InputAction @SelectionGroup6 => m_Wrapper.m_Player_SelectionGroup6;
        public InputAction @SelectionGroup7 => m_Wrapper.m_Player_SelectionGroup7;
        public InputAction @SelectionGroup8 => m_Wrapper.m_Player_SelectionGroup8;
        public InputAction @SelectionGroup9 => m_Wrapper.m_Player_SelectionGroup9;
        public InputAction @SelectionGroup10 => m_Wrapper.m_Player_SelectionGroup10;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @SendCommand.started += instance.OnSendCommand;
            @SendCommand.performed += instance.OnSendCommand;
            @SendCommand.canceled += instance.OnSendCommand;
            @EnableCommendQueuing.started += instance.OnEnableCommendQueuing;
            @EnableCommendQueuing.performed += instance.OnEnableCommendQueuing;
            @EnableCommendQueuing.canceled += instance.OnEnableCommendQueuing;
            @Cancel.started += instance.OnCancel;
            @Cancel.performed += instance.OnCancel;
            @Cancel.canceled += instance.OnCancel;
            @SelectSame.started += instance.OnSelectSame;
            @SelectSame.performed += instance.OnSelectSame;
            @SelectSame.canceled += instance.OnSelectSame;
            @StartSelecting.started += instance.OnStartSelecting;
            @StartSelecting.performed += instance.OnStartSelecting;
            @StartSelecting.canceled += instance.OnStartSelecting;
            @StopSelecting.started += instance.OnStopSelecting;
            @StopSelecting.performed += instance.OnStopSelecting;
            @StopSelecting.canceled += instance.OnStopSelecting;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @SaveSelectionGroup.started += instance.OnSaveSelectionGroup;
            @SaveSelectionGroup.performed += instance.OnSaveSelectionGroup;
            @SaveSelectionGroup.canceled += instance.OnSaveSelectionGroup;
            @SelectionGroup1.started += instance.OnSelectionGroup1;
            @SelectionGroup1.performed += instance.OnSelectionGroup1;
            @SelectionGroup1.canceled += instance.OnSelectionGroup1;
            @SelectionGroup2.started += instance.OnSelectionGroup2;
            @SelectionGroup2.performed += instance.OnSelectionGroup2;
            @SelectionGroup2.canceled += instance.OnSelectionGroup2;
            @SelectionGroup3.started += instance.OnSelectionGroup3;
            @SelectionGroup3.performed += instance.OnSelectionGroup3;
            @SelectionGroup3.canceled += instance.OnSelectionGroup3;
            @SelectionGroup4.started += instance.OnSelectionGroup4;
            @SelectionGroup4.performed += instance.OnSelectionGroup4;
            @SelectionGroup4.canceled += instance.OnSelectionGroup4;
            @SelectionGroup5.started += instance.OnSelectionGroup5;
            @SelectionGroup5.performed += instance.OnSelectionGroup5;
            @SelectionGroup5.canceled += instance.OnSelectionGroup5;
            @SelectionGroup6.started += instance.OnSelectionGroup6;
            @SelectionGroup6.performed += instance.OnSelectionGroup6;
            @SelectionGroup6.canceled += instance.OnSelectionGroup6;
            @SelectionGroup7.started += instance.OnSelectionGroup7;
            @SelectionGroup7.performed += instance.OnSelectionGroup7;
            @SelectionGroup7.canceled += instance.OnSelectionGroup7;
            @SelectionGroup8.started += instance.OnSelectionGroup8;
            @SelectionGroup8.performed += instance.OnSelectionGroup8;
            @SelectionGroup8.canceled += instance.OnSelectionGroup8;
            @SelectionGroup9.started += instance.OnSelectionGroup9;
            @SelectionGroup9.performed += instance.OnSelectionGroup9;
            @SelectionGroup9.canceled += instance.OnSelectionGroup9;
            @SelectionGroup10.started += instance.OnSelectionGroup10;
            @SelectionGroup10.performed += instance.OnSelectionGroup10;
            @SelectionGroup10.canceled += instance.OnSelectionGroup10;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @SendCommand.started -= instance.OnSendCommand;
            @SendCommand.performed -= instance.OnSendCommand;
            @SendCommand.canceled -= instance.OnSendCommand;
            @EnableCommendQueuing.started -= instance.OnEnableCommendQueuing;
            @EnableCommendQueuing.performed -= instance.OnEnableCommendQueuing;
            @EnableCommendQueuing.canceled -= instance.OnEnableCommendQueuing;
            @Cancel.started -= instance.OnCancel;
            @Cancel.performed -= instance.OnCancel;
            @Cancel.canceled -= instance.OnCancel;
            @SelectSame.started -= instance.OnSelectSame;
            @SelectSame.performed -= instance.OnSelectSame;
            @SelectSame.canceled -= instance.OnSelectSame;
            @StartSelecting.started -= instance.OnStartSelecting;
            @StartSelecting.performed -= instance.OnStartSelecting;
            @StartSelecting.canceled -= instance.OnStartSelecting;
            @StopSelecting.started -= instance.OnStopSelecting;
            @StopSelecting.performed -= instance.OnStopSelecting;
            @StopSelecting.canceled -= instance.OnStopSelecting;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @SaveSelectionGroup.started -= instance.OnSaveSelectionGroup;
            @SaveSelectionGroup.performed -= instance.OnSaveSelectionGroup;
            @SaveSelectionGroup.canceled -= instance.OnSaveSelectionGroup;
            @SelectionGroup1.started -= instance.OnSelectionGroup1;
            @SelectionGroup1.performed -= instance.OnSelectionGroup1;
            @SelectionGroup1.canceled -= instance.OnSelectionGroup1;
            @SelectionGroup2.started -= instance.OnSelectionGroup2;
            @SelectionGroup2.performed -= instance.OnSelectionGroup2;
            @SelectionGroup2.canceled -= instance.OnSelectionGroup2;
            @SelectionGroup3.started -= instance.OnSelectionGroup3;
            @SelectionGroup3.performed -= instance.OnSelectionGroup3;
            @SelectionGroup3.canceled -= instance.OnSelectionGroup3;
            @SelectionGroup4.started -= instance.OnSelectionGroup4;
            @SelectionGroup4.performed -= instance.OnSelectionGroup4;
            @SelectionGroup4.canceled -= instance.OnSelectionGroup4;
            @SelectionGroup5.started -= instance.OnSelectionGroup5;
            @SelectionGroup5.performed -= instance.OnSelectionGroup5;
            @SelectionGroup5.canceled -= instance.OnSelectionGroup5;
            @SelectionGroup6.started -= instance.OnSelectionGroup6;
            @SelectionGroup6.performed -= instance.OnSelectionGroup6;
            @SelectionGroup6.canceled -= instance.OnSelectionGroup6;
            @SelectionGroup7.started -= instance.OnSelectionGroup7;
            @SelectionGroup7.performed -= instance.OnSelectionGroup7;
            @SelectionGroup7.canceled -= instance.OnSelectionGroup7;
            @SelectionGroup8.started -= instance.OnSelectionGroup8;
            @SelectionGroup8.performed -= instance.OnSelectionGroup8;
            @SelectionGroup8.canceled -= instance.OnSelectionGroup8;
            @SelectionGroup9.started -= instance.OnSelectionGroup9;
            @SelectionGroup9.performed -= instance.OnSelectionGroup9;
            @SelectionGroup9.canceled -= instance.OnSelectionGroup9;
            @SelectionGroup10.started -= instance.OnSelectionGroup10;
            @SelectionGroup10.performed -= instance.OnSelectionGroup10;
            @SelectionGroup10.canceled -= instance.OnSelectionGroup10;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // Camera
    private readonly InputActionMap m_Camera;
    private List<ICameraActions> m_CameraActionsCallbackInterfaces = new List<ICameraActions>();
    private readonly InputAction m_Camera_Focus;
    private readonly InputAction m_Camera_Zoom;
    private readonly InputAction m_Camera_ScreenPosition;
    private readonly InputAction m_Camera_CameraRotationDirection;
    private readonly InputAction m_Camera_EnableCameraRotation;
    public struct CameraActions
    {
        private @PlayerControls m_Wrapper;
        public CameraActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Focus => m_Wrapper.m_Camera_Focus;
        public InputAction @Zoom => m_Wrapper.m_Camera_Zoom;
        public InputAction @ScreenPosition => m_Wrapper.m_Camera_ScreenPosition;
        public InputAction @CameraRotationDirection => m_Wrapper.m_Camera_CameraRotationDirection;
        public InputAction @EnableCameraRotation => m_Wrapper.m_Camera_EnableCameraRotation;
        public InputActionMap Get() { return m_Wrapper.m_Camera; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CameraActions set) { return set.Get(); }
        public void AddCallbacks(ICameraActions instance)
        {
            if (instance == null || m_Wrapper.m_CameraActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CameraActionsCallbackInterfaces.Add(instance);
            @Focus.started += instance.OnFocus;
            @Focus.performed += instance.OnFocus;
            @Focus.canceled += instance.OnFocus;
            @Zoom.started += instance.OnZoom;
            @Zoom.performed += instance.OnZoom;
            @Zoom.canceled += instance.OnZoom;
            @ScreenPosition.started += instance.OnScreenPosition;
            @ScreenPosition.performed += instance.OnScreenPosition;
            @ScreenPosition.canceled += instance.OnScreenPosition;
            @CameraRotationDirection.started += instance.OnCameraRotationDirection;
            @CameraRotationDirection.performed += instance.OnCameraRotationDirection;
            @CameraRotationDirection.canceled += instance.OnCameraRotationDirection;
            @EnableCameraRotation.started += instance.OnEnableCameraRotation;
            @EnableCameraRotation.performed += instance.OnEnableCameraRotation;
            @EnableCameraRotation.canceled += instance.OnEnableCameraRotation;
        }

        private void UnregisterCallbacks(ICameraActions instance)
        {
            @Focus.started -= instance.OnFocus;
            @Focus.performed -= instance.OnFocus;
            @Focus.canceled -= instance.OnFocus;
            @Zoom.started -= instance.OnZoom;
            @Zoom.performed -= instance.OnZoom;
            @Zoom.canceled -= instance.OnZoom;
            @ScreenPosition.started -= instance.OnScreenPosition;
            @ScreenPosition.performed -= instance.OnScreenPosition;
            @ScreenPosition.canceled -= instance.OnScreenPosition;
            @CameraRotationDirection.started -= instance.OnCameraRotationDirection;
            @CameraRotationDirection.performed -= instance.OnCameraRotationDirection;
            @CameraRotationDirection.canceled -= instance.OnCameraRotationDirection;
            @EnableCameraRotation.started -= instance.OnEnableCameraRotation;
            @EnableCameraRotation.performed -= instance.OnEnableCameraRotation;
            @EnableCameraRotation.canceled -= instance.OnEnableCameraRotation;
        }

        public void RemoveCallbacks(ICameraActions instance)
        {
            if (m_Wrapper.m_CameraActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICameraActions instance)
        {
            foreach (var item in m_Wrapper.m_CameraActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CameraActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CameraActions @Camera => new CameraActions(this);

    // Menu
    private readonly InputActionMap m_Menu;
    private List<IMenuActions> m_MenuActionsCallbackInterfaces = new List<IMenuActions>();
    private readonly InputAction m_Menu_Close;
    private readonly InputAction m_Menu_ScreenPosition;
    public struct MenuActions
    {
        private @PlayerControls m_Wrapper;
        public MenuActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Close => m_Wrapper.m_Menu_Close;
        public InputAction @ScreenPosition => m_Wrapper.m_Menu_ScreenPosition;
        public InputActionMap Get() { return m_Wrapper.m_Menu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuActions set) { return set.Get(); }
        public void AddCallbacks(IMenuActions instance)
        {
            if (instance == null || m_Wrapper.m_MenuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MenuActionsCallbackInterfaces.Add(instance);
            @Close.started += instance.OnClose;
            @Close.performed += instance.OnClose;
            @Close.canceled += instance.OnClose;
            @ScreenPosition.started += instance.OnScreenPosition;
            @ScreenPosition.performed += instance.OnScreenPosition;
            @ScreenPosition.canceled += instance.OnScreenPosition;
        }

        private void UnregisterCallbacks(IMenuActions instance)
        {
            @Close.started -= instance.OnClose;
            @Close.performed -= instance.OnClose;
            @Close.canceled -= instance.OnClose;
            @ScreenPosition.started -= instance.OnScreenPosition;
            @ScreenPosition.performed -= instance.OnScreenPosition;
            @ScreenPosition.canceled -= instance.OnScreenPosition;
        }

        public void RemoveCallbacks(IMenuActions instance)
        {
            if (m_Wrapper.m_MenuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMenuActions instance)
        {
            foreach (var item in m_Wrapper.m_MenuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MenuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MenuActions @Menu => new MenuActions(this);
    public interface IPlayerActions
    {
        void OnSendCommand(InputAction.CallbackContext context);
        void OnEnableCommendQueuing(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnSelectSame(InputAction.CallbackContext context);
        void OnStartSelecting(InputAction.CallbackContext context);
        void OnStopSelecting(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnSaveSelectionGroup(InputAction.CallbackContext context);
        void OnSelectionGroup1(InputAction.CallbackContext context);
        void OnSelectionGroup2(InputAction.CallbackContext context);
        void OnSelectionGroup3(InputAction.CallbackContext context);
        void OnSelectionGroup4(InputAction.CallbackContext context);
        void OnSelectionGroup5(InputAction.CallbackContext context);
        void OnSelectionGroup6(InputAction.CallbackContext context);
        void OnSelectionGroup7(InputAction.CallbackContext context);
        void OnSelectionGroup8(InputAction.CallbackContext context);
        void OnSelectionGroup9(InputAction.CallbackContext context);
        void OnSelectionGroup10(InputAction.CallbackContext context);
    }
    public interface ICameraActions
    {
        void OnFocus(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
        void OnScreenPosition(InputAction.CallbackContext context);
        void OnCameraRotationDirection(InputAction.CallbackContext context);
        void OnEnableCameraRotation(InputAction.CallbackContext context);
    }
    public interface IMenuActions
    {
        void OnClose(InputAction.CallbackContext context);
        void OnScreenPosition(InputAction.CallbackContext context);
    }
}
